### ISSUE TITLE
mac 

### ISSUE THREAD

**Issue by qazxsqazwsx** [Qihoo360/phptrace#13]
gcc -g -Wall -O2 -fno-strict-aliasing -D_GNU_SOURCE -I/usr/local/src/phptrace-master/cmdtool/../common -I/usr/local/src/phptrace-master/cmdtool/../common/sds -c sys_trace.c -o sys_trace.o 
sys_trace.c:7:20: error: use of undeclared identifier 'PTRACE_ATTACH'
    if (0 > ptrace(PTRACE_ATTACH, pid, 0, 0)) {
                   ^
sys_trace.c:16:20: error: use of undeclared identifier 'PTRACE_DETACH'
    if (0 > ptrace(PTRACE_DETACH, pid, (void *) 1, 0)) {
                   ^
sys_trace.c:38:20: error: use of undeclared identifier 'PTRACE_PEEKDATA'
    *data = ptrace(PTRACE_PEEKDATA, pid, (void *) addr, 0);
                   ^
sys_trace.c:83:20: warning: implicit declaration of function 'kill' is invalid
      in C99 [-Wimplicit-function-declaration]
            return kill(pid, sig);
                   ^
1 warning and 3 errors generated.
make: *** [sys_trace.o] Error 1

**Comment by loyating** [comment]
如题。。
gcc -g -Wall -O2 -fno-strict-aliasing -D_GNU_SOURCE -I/Users/loyating/Downloads/php/phptrace/cmdtool/../common -I/Users/loyating/Downloads/php/phptrace/cmdtool/../common/sds -c sys_trace.c -o sys_trace.o 
sys_trace.c:7:20: error: use of undeclared identifier 'PTRACE_ATTACH'
    if (0 > ptrace(PTRACE_ATTACH, pid, 0, 0)) {
                   ^
sys_trace.c:16:20: error: use of undeclared identifier 'PTRACE_DETACH'
    if (0 > ptrace(PTRACE_DETACH, pid, (void *) 1, 0)) {
                   ^
sys_trace.c:38:20: error: use of undeclared identifier 'PTRACE_PEEKDATA'
    *data = ptrace(PTRACE_PEEKDATA, pid, (void *) addr, 0);
                   ^
sys_trace.c:83:20: warning: implicit declaration of function 'kill' is invalid
      in C99 [-Wimplicit-function-declaration]
            return kill(pid, sig);
                   ^
1 warning and 3 errors generated.
make: *** [sys_trace.o] Error 1

**Comment by shafreeck** [comment]
master分支暂时还不支持Mac OS X， 最新的nightly已经支持， 接下来release的版本将支持Mac OS X， 等不及的用户可以先试用nightly分支。
