### ISSUE TITLE
update trace mmap filename failed

### ISSUE THREAD

**Issue by tangxunye** [Qihoo360/phptrace#15]
mac，php5.5.18，iss11分支
trace到353813行后
会产生错误
TRACE ERROR: update trace mmap filename failed

**Comment by shafreeck** [comment]
@tangxunye  感谢反馈

**Comment by flabby** [comment]
@tangxunye , 你可以使用最新的nightly分支的代码，已经修复了filename更新失败的bug；

We have fixed this bug. You can try our latest code in nightly branch.

**Comment by shafreeck** [comment]
resolved by https://github.com/Qihoo360/phptrace/commit/417bd1ede0f44e2912e3820c0344f7c8745beae7
