### ISSUE TITLE
实测phptrace对fpm环境完全无用

### ISSUE THREAD

**Issue by microhuang** [Qihoo360/phptrace#16]
刻意调整pm.start_servers=1、pm.max_spare_servers=1、pm.min_spare_servers=1。
phptrace -p <pid>、phptrace -p <pid> -s均无任何反应。

**Comment by microhuang** [comment]
版本：php5.5.20

**Comment by shafreeck** [comment]
确认启用扩展了吗？

**Comment by microhuang** [comment]
启用了。运行无报错，无任何反应。

**Comment by shafreeck** [comment]
@microhuang  你好，`phptrace -p <PID>` 中的`PID` 必须是worker进程ID， 请确认一下您使用的master进程ID还是worker进程ID

**Comment by microhuang** [comment]
worker pid、master pid都试过。

**Comment by joostshao** [comment]
1:
sudo ./php-trace -p  23004 -s 
phptrace 0.2.0 stable, published by 360 infra webcore team
INVALID PARAM: address info not enough


2:
sudo ./phptrace -p  23004 -s
phptrace 0.2.0 stable, published by 360 infra webcore team
INVALID PARAM: sapi-globals: <sapi_globals>


打印堆栈信息失败。

**Comment by click1** [comment]
环境PHP Version 5.5.9-1ubuntu4.4
框架 yaf
1、在php-fpm环境下，调试成功，但是加载了调试后，页面就会502错误，
2、打印出来的信息完全没有作用，是不是对于yaf扩展这样的框架 调试

**Comment by shafreeck** [comment]
@joostshao  你好，感谢反馈， 不过你所述的跟这个issue无关， 请另开一个issue， 并附上尽量详细的信息， 比如操作系统， PHP版本， php-config的输出等等

**Comment by yinchuan** [comment]
简单测试了一下。
CentOS 6.6，selinux off，php-fpm.x86_64 5.5.21-1.el6.remi，trace 正常。打印 stack of function call 报 'can not print php stack'。

**Comment by shafreeck** [comment]
@yinchuan `stack`功能用以打印PHP函数的调用栈， 如果PHP当前没有执行任何脚本， 可能无法打出调用栈。
