### ISSUE TITLE
mac 编译cmdtool 报错

### ISSUE THREAD

**Issue by rickyliyi** [Qihoo360/phptrace#2]
机器：mac air 
php: 5.6.3
cd 到 cmdtool 目录
make 
报如下错误
gcc -g -Wall -O2 -fno-strict-aliasing -D_GNU_SOURCE -I/Users/xxx/work/study/php/phptrace-master/cmdtool/../common -I/Users/xxx/work/study/php/phptrace-master/cmdtool/../common/sds -c sys_trace.c -o sys_trace.o
sys_trace.c:7:20: error: use of undeclared identifier 'PTRACE_ATTACH'
    if (0 > ptrace(PTRACE_ATTACH, pid, 0, 0)) {
                   ^
sys_trace.c:16:20: error: use of undeclared identifier 'PTRACE_DETACH'
    if (0 > ptrace(PTRACE_DETACH, pid, (void *) 1, 0)) {
                   ^
sys_trace.c:38:20: error: use of undeclared identifier 'PTRACE_PEEKDATA'
    *data = ptrace(PTRACE_PEEKDATA, pid, (void *) addr, 0);
                   ^
sys_trace.c:83:20: warning: implicit declaration of function 'kill' is invalid in C99 [-Wimplicit-function-declaration]
            return kill(pid, sig);
                   ^
1 warning and 3 errors generated.
make: *** [sys_trace.o] Error 1

**Comment by shafreeck** [comment]
**notice**
由于代码开源前使用gitlab的issue系统， 因此这里自动关联的commit https://github.com/Qihoo360/phptrace/commit/67189a3fcf10579697cc3357e309f94492c10cb3 其实不正确。

**Comment by shafreeck** [comment]
resolved https://github.com/Qihoo360/phptrace/commit/150bcf8cdaa2fcd651d3136b086bf1a01a33ca25

**Comment by loyating** [comment]
等待mac
