### ISSUE TITLE
对于yaf框架能用吗？还是我的姿势不对？？？

### ISSUE THREAD

**Issue by click1** [Qihoo360/phptrace#20]
环境PHP Version 5.5.9-1ubuntu4.4
框架 yaf
1、在php-fpm环境下，调试成功，但是加载了调试后，页面就会502错误，
2、打印出来的信息完全没有作用，是不是对于yaf扩展这样的框架 调试

**Comment by shafreeck** [comment]
你好， phptrace 支持yaf， 502 错误是不是因为有php进程挂掉了？ 能否提供一些详细信息： phptrace 版本， php-fpm 进程是否core掉， yaf 版本 等
