### ISSUE TITLE
[feature request] add support to trace none long-running script started from cli

### ISSUE THREAD

**Issue by yinchuan** [Qihoo360/phptrace#21]
usage like strace, phpstrace php /path/to/script.php

**Comment by shafreeck** [comment]
run `php -dphptrace.dotrace=1 /path/to/scrip.php`, That 's  what you want !

**Comment by netroby** [comment]
phptrace is an extension for PHP,  so do not have the ability to run as dedicated executable command. Or you can wrap it by your own shell scripts
