### ISSUE TITLE
make: *** No rule to make target `/usr/local/src/phptrace-0.2.2/phpext/common/phptrace_mmap.c', 

### ISSUE THREAD

**Issue by Hwavin** [Qihoo360/phptrace#27]
**Darwin 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64**

/usr/local/src/phptrace-0.2.2/phpext$ sudo ./configure --with-php-config=/usr/local/opt/php55/bin/php-config 
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin14.1.0
checking host system type... x86_64-apple-darwin14.1.0
checking target system type... x86_64-apple-darwin14.1.0
checking for PHP prefix... /usr/local/Cellar/php55/5.5.19
checking for PHP includes... -I/usr/local/Cellar/php55/5.5.19/include/php -I/usr/local/Cellar/php55/5.5.19/include/php/main -I/usr/local/Cellar/php55/5.5.19/include/php/TSRM -I/usr/local/Cellar/php55/5.5.19/include/php/Zend -I/usr/local/Cellar/php55/5.5.19/include/php/ext -I/usr/local/Cellar/php55/5.5.19/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/Cellar/php55/5.5.19/lib/php/extensions/no-debug-non-zts-20121212
checking for PHP installed headers prefix... /usr/local/Cellar/php55/5.5.19/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable phptrace support... yes, shared
checking for ld used by cc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 196608
checking command to parse /usr/bin/nm output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking if cc supports -fno-rtti -fno-exceptions... yes
checking for cc option to produce PIC... -fno-common
checking if cc PIC flag -fno-common works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin14.1.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
joewong /usr/local/src/phptrace-0.2.2/phpext$ sudo make
/bin/sh /usr/local/src/phptrace-0.2.2/phpext/libtool --mode=compile cc  -I. -I/usr/local/src/phptrace-0.2.2/phpext -DPHP_ATOM_INC -I/usr/local/src/phptrace-0.2.2/phpext/include -I/usr/local/src/phptrace-0.2.2/phpext/main -I/usr/local/src/phptrace-0.2.2/phpext -I/usr/local/Cellar/php55/5.5.19/include/php -I/usr/local/Cellar/php55/5.5.19/include/php/main -I/usr/local/Cellar/php55/5.5.19/include/php/TSRM -I/usr/local/Cellar/php55/5.5.19/include/php/Zend -I/usr/local/Cellar/php55/5.5.19/include/php/ext -I/usr/local/Cellar/php55/5.5.19/include/php/ext/date/lib -I/usr/local/src/phptrace-0.2.2/common  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/src/phptrace-0.2.2/phpext/phptrace.c -o phptrace.lo 
mkdir .libs
 cc -I. -I/usr/local/src/phptrace-0.2.2/phpext -DPHP_ATOM_INC -I/usr/local/src/phptrace-0.2.2/phpext/include -I/usr/local/src/phptrace-0.2.2/phpext/main -I/usr/local/src/phptrace-0.2.2/phpext -I/usr/local/Cellar/php55/5.5.19/include/php -I/usr/local/Cellar/php55/5.5.19/include/php/main -I/usr/local/Cellar/php55/5.5.19/include/php/TSRM -I/usr/local/Cellar/php55/5.5.19/include/php/Zend -I/usr/local/Cellar/php55/5.5.19/include/php/ext -I/usr/local/Cellar/php55/5.5.19/include/php/ext/date/lib -I/usr/local/src/phptrace-0.2.2/common -DHAVE_CONFIG_H -g -O2 -c /usr/local/src/phptrace-0.2.2/phpext/phptrace.c  -fno-common -DPIC -o .libs/phptrace.o
/usr/local/src/phptrace-0.2.2/phpext/phptrace.c:491:25: warning: format
      specifies type 'unsigned long' but the argument has type 'uint64_t' (aka
      'unsigned long long') [-Wformat]
    printf("%lu %d %f ",record->seq, record->level, record->start_time/1...
            ~~~         ^~~~~~~~~~~
            %llu
1 warning generated.
make: *** No rule to make target `/usr/local/src/phptrace-0.2.2/phpext/common/phptrace_mmap.c', needed by `common/phptrace_mmap.lo'.  Stop.

**Comment by shafreeck** [comment]
Hi, 这是因为phpize生成的脚本，对符号连接处理不好的缘故， 您可以删掉并重新git clone 编译， 也可以将phptrace/ 下的common目录，复制到phptrace/phpext目录下
