### ISSUE TITLE
fpm 模式, 多进程, 怎么调试? 根本不知道请求在那个进程处理

### ISSUE THREAD

**Issue by fengqi** [Qihoo360/phptrace#28]
根本不知道请求分配到哪个进程了, 我尝试每个 pid 改跟踪, 输出内容不一样, 而且如果进程数是动态的就更难办了, 线上环境是不可能只有一个进程的啊.

**Comment by monque** [comment]
能否描述一下你需要trace的内容？就是说你想trace什么内容

**Comment by fengqi** [comment]
执行过程啊, phptrace 不就是做这个吗, 我是想知道有很多个进程的情况下该怎么办, 是否能做到随意拿一个 pid 都可以.
我印象中 fpm 每个进程处理的请求是均匀分配的.

**Comment by monque** [comment]
fpm确实如你所说，目前phptrace只能指定**一个pid**进行trace，所以肯定达不到随便拿一个pid就可以trace到全部的效果，而且关于这么做的价值目前也不是很明确。

对于你提到的有多个进程的情况下该怎么办，如果你能够比较清晰的描述你在多进程下想trace什么内容的话可能我会好回答一些。

我大概按照目前有过的应用场景来说下，希望有你需要的功能：

- PHP机器负载整体偏高，这种情况下你可以随意trace一个进程一段时间，这样通常可以拿到这一时间段的调用情况，通过分析数据大概能够发现运行较慢的调用。
- 通过ps或者top看到某一个进程卡住或者是CPU占用很高，你可以单独去trace这个pid。

**Comment by fengqi** [comment]
了解了, 我刚开始折腾 phptrace, 还没有具体的案例, 只是在测试过程中发现这个而已, 你说的那几个场景也的确已经能满足大部分需要了.
谢谢了.

**Comment by monque** [comment]
你可以加到讨论的群里面，沟通起来更及时一些。
如果有啥好的建议也欢迎提出来。

**Comment by fengqi** [comment]
Ok 等下加进去
