### ISSUE TITLE
扩展名称不是phptrace.so  而是 trace.so

### ISSUE THREAD

**Issue by wwek** [Qihoo360/phptrace#29]
配置后发现没起作用 
 phptrace -p 9059
CONTROL ERROR: cannot open control mmap file /tmp/phptrace.ctrl (No such file or directory)

检查后发现 .so文件名称为 trace.so

提供的例子是
[phptrace] 
extension=phptrace.so 
phptrace.enabled = 1
实际上 这里应该改为 
extension=trace.so

**Comment by monque** [comment]
感谢反馈，已经更新了新的readme

**Comment by mickelfeng** [comment]
就一个名字而已。

**Comment by changeYi** [comment]
嗨，还是没有改过来。
https://github.com/Qihoo360/phptrace/wiki/PHP-Trace-%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97

**Comment by monque** [comment]
以readme为准吧
