### ISSUE TITLE
php5-fpm

### ISSUE THREAD

**Issue by MartyIX** [Qihoo360/phptrace#35]
Can I use phptrace to trace scripts that were run by php5-fpm service?

Thank you

**Comment by monque** [comment]
Definitely yes, but you must trace fpm worker process.

**Comment by codvio** [comment]
I trace worker processes but nothing happens:

```
root     18029  0.3  1.3 321076 27208 ?        Ss   11:50   0:00 php-fpm: master process (/etc/php5/fpm/php-fpm.conf)                    
www-data 18033  0.0  0.4 321076  8256 ?        S    11:50   0:00  \_ php-fpm: pool www                                                       
www-data 18034  0.0  0.4 321076  8256 ?        S    11:50   0:00  \_ php-fpm: pool www 
```

Both `./phptrace -p 18033` and `./phptrace -p 18034` print nothing.
```

**Comment by Lupul** [comment]
can you read the status of the php process ?

phptrace -s -p xxx
