### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by sarathsp06** [Qihoo360/phptrace#36]
I have installed the tool and tried the sample check its not working.
Not Working  : By not working i mean there are no trace i can see.
I have added the extension and php.ini parsing and execution where susccessfull

**Comment by monque** [comment]
Could you paste command that you run?

**Comment by sarathsp06** [comment]
Hi @monque  its been around 8 months since i used it.I must have followed the getting started / quick started if any.
FYA am using ubuntu 14.04 

```
uname -a 
Linux sarath-exotel 3.13.0-65-generic #105-Ubuntu SMP Mon Sep 21 18:50:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by monque** [comment]
Thanks, I'll check on ubuntu :smile:
