### ISSUE TITLE
can use phptrace to trace Trojan file running?

### ISSUE THREAD

**Issue by mickelfeng** [Qihoo360/phptrace#37]
sometimes my website is hacked by somebody.  he uses Trojan file to generate so many html files .
I want to use this tool to monitor the trace of Trojan file runing.

**Comment by monque** [comment]
The goal you wanted is too ambiguity. I plan add a filter of function call, this will make it trace specified call such as `eval()`, `system()`, does this feature solve your problem ?

**Comment by mickelfeng** [comment]
yes. that`s great.
