### ISSUE TITLE
关于参数选项

### ISSUE THREAD

**Issue by leeir** [Qihoo360/phptrace#39]
-o outfile           -- write the trace data to file in specified format
 --format format      -- specify the format when -o option is set. Legal values is json for now
当我选择用格式化输出到文件  这个json格文件该如何书写、需要官方给出一个简单的demo

还有就是我用-w这个选项数据是写ok的  但是都是一些乱码 不知为何？ 望解答 谢谢！

**Comment by monque** [comment]
像用-w一样，-o需要和--format一起使用，例如：-o demo.json --format json

*Yuchen Wang*

2015-09-21 17:39 GMT+08:00 reflux <notifications@github.com>:
