### ISSUE TITLE
CONTROL ERROR: cannot open control mmap file /tmp/phptrace.ctrl (null)

### ISSUE THREAD

**Issue by tdifg** [Qihoo360/phptrace#42]
编译均正常，修改php.ini新增：
[phptrace]        
externsion=trace.so
phptrace.enabled=1

运行readme示例，
➜  cmdtool  ./phptrace -p $!                                         
CONTROL ERROR: cannot open control mmap file /tmp/phptrace.ctrl (null)

**Comment by magicII** [comment]
一样的问题.要如何解决呢.

**Comment by retanoj** [comment]
same question
centos 7, php5.6.24
