### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by simple4wan** [Qihoo360/phptrace#43]
OS debian 8.1
PHP VERSION PHP 5.6.13-0+deb8u1 (cli)

➜  ~  php -r 'for ($i = 0; $i < 100; $i++) usleep(100000);' &
[1] 4362
➜  ~  phptrace -s -p 4362
Memory
usage: 114180
peak_usage: 116336
real_usage: 262144
real_peak_usage: 262144

Request
request_script: -
request_time: 1445305080.264987

Stack
#1    usleep(100000) at [:1]

**\* Error in `/usr/bin/trace-php': free(): invalid pointer: 0x091640f0 ***
/usr/bin/phptrace: line 146:  4371 Aborted                 "$SCRIPT_PATH/trace-php" $@
STACK ERROR: Can not fetch PHP status from extension, fallback to get stack by ptrace
can not print php stack

**Comment by monque** [comment]
Fixed in new version.
