### ISSUE TITLE
多次执行phptrace时有时无法获得输出

### ISSUE THREAD

**Issue by tdifg** [Qihoo360/phptrace#45]
执行的命令都是phptrace -p xxxx，但是多次执行的时候，间隔几次无法获得输出，其余正常。

**Comment by monque** [comment]
能否提供更详细的信息？

这种情况通常是因为被trace的进程当时没有处理请求或运行。

**Comment by monque** [comment]
可能受创建mmap文件影响，新版本中已更新传输机制
