### ISSUE TITLE
TRACE ERROR: Can not open /tmp/phptrace.comm.5093 to read, No such file or directory!

### ISSUE THREAD

**Issue by aimchina** [Qihoo360/phptrace#46]
报错

**Comment by yocome** [comment]
同样错误：
$ ./phptrace -p 7471 -s
TRACE ERROR: Can not open /tmp/phptrace.comm.7471 to read, No such file or directory!
STACK ERROR: Can not fetch PHP status from extension, fallback to get stack by ptrace
can not print php stack

**Comment by azonwan** [comment]
同样的问题，已经困扰很久了

**Comment by xxfaxy** [comment]
同样的错误呢

**Comment by xxfaxy** [comment]
TRACE ERROR: Can not open /tmp/phptrace.comm.22851 to read, No such file or directory!
STACK ERROR: Can not fetch PHP status from extension, fallback to get stack by ptrace
can not print php stack

**Comment by flyfengye** [comment]
同样的错误，求大家解答~
# ./phptrace -p 8287 没问题，可以正常显示跟踪信息，但是
# ./phptrace -s -p 8287 的时候，就报错：
TRACE ERROR: Can not open /tmp/phptrace.comm.8287 to read, No such file or directory!
STACK ERROR: Can not fetch PHP status from extension, fallback to get stack by ptrace
STACK ERROR: dump status failed. maybe the process is not executing a php script

**Comment by monque** [comment]
导致这个问题的原因可能是，被trace的进程当前没有处理请求。

不带`-s`时可以是因为trace模式下不会有等待PHP响应的超时时间，所以只要有请求就可以trace。

带`-s`是为了打印当前的状态，为了保证这个实时性，这里有个超时时间。

如果对应的PHP进程没能在超时时间内响应，会降级使用系统调用的`ptrace`进行处理。

如果这个PHP进程仍然没有在处理请求，则会报上文中提到的错误。
