### ISSUE TITLE
执行 ./phptrace -p 7773 -s提示 Can not fetch PHP status from extension

### ISSUE THREAD

**Issue by lyongdee** [Qihoo360/phptrace#51]
提示异常：
TRACE ERROR: Can not open /tmp/phptrace.comm.7773 to read, No such file or directory!
STACK ERROR: Can not fetch PHP status from extension, fallback to get stack by ptrace
can not print php stack

7773是master process.

**Comment by monque** [comment]
At this moment, phptrace can not trace master process of php-fpm.

because the fpm master process not running as a real PHP process.

So, you should trace the worker process, or try the nightly version and trace all process.
