### ISSUE TITLE
Other examples of how to use phptrace?

### ISSUE THREAD

**Issue by eriksank** [Qihoo360/phptrace#52]
The canonical example works fine:

```
$ php -r 'for ($i = 0; $i < 100; $i++) usleep(10000);' & ./phptrace -p $!
```

After the following small modification, the tracing program does not output anything:

```
$ php -r 'for ($i = 0; $i < 100; $i++) echo "$i\n";' & ./phptrace -p $!
```

By the time phptrace gets called, in my impression, the program has terminated already. Any example of how to make it work anyway?

**Comment by monque** [comment]
Your conclusion is right, the second program did not output anything,
because PHP process run too short, so phptrace can not catch a function
call.

But you can trace a running php-fpm process to monitor a request.

and I suggest you try the nightly version, it support trace ALL php process
like this `phptrace -p all | grep mysql`

hope you like it.

*Yuchen Wang*

2016-03-12 13:30 GMT+08:00 Erik Poupaert <notifications@github.com>:

**Comment by eriksank** [comment]
Super! What I may really need, is something like this:

$ phptrace -prog myprogram.php

Which would start executing myprogram.php and trace *only* that program. Another possibility would of course be:

$ phptrace -inline 'for ($i = 0; $i < 100; $i++) echo "$i\n";'

I actually really need something like phptrace because it would be the core building brick for replicating something like this in PHP:

[https://lcamtuf.blogspot.com/2014/11/pulling-jpegs-out-of-thin-air.html](https://lcamtuf.blogspot.com/2014/11/pulling-jpegs-out-of-thin-air.html)

These guys nicely solved the problem for native binaries, but I think it can also be solved for PHP programs:

input1 --> fuzzer --> (output1, trace1)
input2 --> fuzzer --> (output2, trace2)
input3 --> fuzzer --> (output3, trace3)

The trace is typically always the same, but if the fuzzer detects that a particular input, say input1, produces a different trace, the fuzzer elaborates on that, by digging up new inputs around input1 :

(input1, output1, trace1) ==> input2

Even with a relatively simple fuzzer, you could detect lots and lots of bugs in PHP scripts. It is very powerful. A good fuzzer will detect that your program requires jpeg files as input and will guess from the reactions of your program what a valid example jpeg file could be. It will "discover" the jpeg file format from that.

**Comment by monque** [comment]
You could simply run by this line 

```
php -d trace.dotrace=1 myprogram.php
```

and that

```
php -d trace.dotrace=1 -r 'for ($i = 0; $i < 100; $i++) echo "$i\n";'
```

It seems meet your requirement, so `trace.dotrace=1` control PHP output trace log directly.

And you point out a good idea for fuzz testing , may be it can make fuzzer works more explicitly with trace data.

please let me know iff phptrace can help you.
