### ISSUE TITLE
[make test failed]

### ISSUE THREAD

**Issue by adxhyt** [Qihoo360/phptrace#54]
FAIL Trace various handlers [tests/trace_004.phpt]
PHP版本是 5.6.12

PHP         : /home/service/php/bin/php
PHP_SAPI    : cli
PHP_VERSION : 5.6.12
ZEND_VERSION: 2.6.0
PHP_OS      : Linux - Linux  2.6.32-888.el6.x86_64 #1 SMP Fri Feb 13 12:14:55 CST 2015 x86_64
INI actual  : /home/work/trace-0.3.0/extension/tmp-php.ini
More .INIs  :
CWD         : /home/work/trace-0.3.0/extension
Extra dirs  :
VALGRIND    : Not used
=====================================================================
TIME START 2016-03-15 11:07:01
=====================================================================
PASS Trace simple call with various types of argument [tests/trace_001.phpt]
PASS Trace include, require, lambda, eval [tests/trace_002.phpt]
PASS Trace Class and Object [tests/trace_003.phpt]
FAIL Trace various handlers [tests/trace_004.phpt]
SKIP Trace signal handler [tests/trace_005.phpt] reason: trace_start() not exists
SKIP Trace call under namespace [tests/trace_006.phpt] reason: trace_start() not exists
SKIP Trace Closure [tests/trace_007.phpt] reason: trace_start() not exists
SKIP Trace magic method __callStatic, __invoke [tests/trace_008.phpt] reason: trace_start() not exists
PASS Trace call recursive [tests/trace_009.phpt]
SKIP Trace call trigger by autoload  < 5.5 [tests/trace_010.phpt] reason: trace_start() not exists
SKIP Trace call trigger by autoload >= 5.5 [tests/trace_011.phpt] reason: trace_start() not exists
SKIP Trace Trait [tests/trace_012.phpt] reason: trace_start() not exists
=====================================================================
TIME END 2016-03-15 11:07:01

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   47
---------------------------------------------------------------------

Number of tests :   12                 5
Tests skipped   :    7 ( 58.3%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    1 (  8.3%) ( 20.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :    4 ( 33.3%) ( 80.0%)

能帮忙看下是环境的问题么？

**Comment by monque** [comment]
能否提供下tests目录下的*.log文件的内容？

**Comment by adxhyt** [comment]
[tests.tar.gz](https://github.com/Qihoo360/phptrace/files/179200/tests.tar.gz)

**Comment by monque** [comment]
是PHP在5.6.12中对于tick handler的调整导致的，已经在nightly版本的phptrace中调整了测试用例 
eea1183b9c928d62fd7a0969c57ca9d644a90276
