### ISSUE TITLE
STACK ERROR: fetch PHP globals address failed

### ISSUE THREAD

**Issue by newbiethetest** [Qihoo360/phptrace#55]
- `root@nood:/tmp/phptrace/cmdtool# ps -aux | grep php-fpm
- root      1963  0.0  0.3 344984 26076 ?        Ss   08:16   0:00 php-fpm: master process               
- www-data  1966  0.0  0.1 344984  8648 ?        S    08:16   0:00 php-fpm: pool www                                                       
- www-data  1967  0.0  0.1 344984  8648 ?        S    08:16   0:00 php-fpm: pool www                                                       
- root      9327  0.0  0.0  12884   968 pts/0    S+   12:18   0:00 grep php-fpm
- `

当我执行 phptrace的时候显示
`root@nood:/tmp/phptrace/cmdtool# phptrace -p 1963 -s
STACK ERROR: fetch PHP globals address failed
`
看了下phpinfo()加载的trace没有问题阿;
trace.data_dir	/tmp	/tmp
trace.dotrace	1	1
trace.enable	1	1

系统:debian7  PHP 5.6.9-0+deb8u1 (cli) 同时运行的还有xdebug不知道会不会影响;

**Comment by newbiethetest** [comment]
最后的证实
原因就是xdebug
而且xdebug会引起各种问题,

**Comment by retanoj** [comment]
same question.
centos 7, php 5.6.24
