### ISSUE TITLE
在php7环境安装好之后无法调试输出

### ISSUE THREAD

**Issue by lijinhuan** [Qihoo360/phptrace#56]
问题描述：
     根据文档github文档正常安装，成功加载扩展，成功编译生成phpstrace命令
     执行phptrace -p php-fpm进程pid   没有任何输出
     phptrace-nightly 版本

备注：
     php7环境下是否需要对php打一些补丁之类的？

**Comment by monque** [comment]
try this and post the output here

```
php -r 'for ($i = 0; $i < 10; $i++) usleep(10000);' &
phptrace -p $!
```

**Comment by lijinhuan** [comment]
[root@iZ23zhmm6umZ extension]# /app/php7/bin/php -r 'for ($i = 0; $i < 10; $i++) usleep(10000);' &
[21] 4469
[root@iZ23zhmm6umZ extension]# /app/php7/bin/phptrace -p $!
/app/php7/bin/phptrace: Process 4469 not exists: No such process
[21]+  Done                    /app/php7/bin/php -r 'for ($i = 0; $i < 10; $i++) usleep(10000);'

把时间弄长一点
[root@iZ23zhmm6umZ extension]# /app/php7/bin/php -r 'for ($i = 0; $i < 10; $i++) usleep(1000000);' &
[21] 4593
[root@iZ23zhmm6umZ extension]# /app/php7/bin/phptrace -p $!
process attached
[pid  4593]    > usleep(1000000) called at [Command line code:1]
[pid  4593]    < usleep(1000000) = NULL called at [Command line code:1] wt: 1.000 ct: 0.000
[pid  4593]    > usleep(1000000) called at [Command line code:1]
[pid  4593]    < usleep(1000000) = NULL called at [Command line code:1] wt: 1.000 ct: 0.000
[pid  4593]    > usleep(1000000) called at [Command line code:1]
[pid  4593]    < usleep(1000000) = NULL called at [Command line code:1] wt: 1.000 ct: 0.000
[pid  4593]    > usleep(1000000) called at [Command line code:1]
[pid  4593]    < usleep(1000000) = NULL called at [Command line code:1] wt: 1.000 ct: 0.000
[pid  4593]    > usleep(1000000) called at [Command line code:1]
[pid  4593]    < usleep(1000000) = NULL called at [Command line code:1] wt: 1.000 ct: 0.000
[pid  4593]    > usleep(1000000) called at [Command line code:1]
[pid  4593]    < usleep(1000000) = NULL called at [Command line code:1] wt: 1.000 ct: 0.000

**Comment by monque** [comment]
这么看起来安装和运行的都正常。

在执行`phptrace -p php-fpm进程pid `时，你确定该进程正在处理请求？

**Comment by lijinhuan** [comment]
奇怪了，可以了，直接刷页面，刷请求不行，非得用ab并发才出来，难道一直没请求，没理由阿

**Comment by monque** [comment]
是这样，直接刷页面如果fpm工作在`dynamic`模式下，这个请求并不一定会由被trace的进程执行。

你可以通过`phptrace -p all`来追踪所有进程

**Comment by lijinhuan** [comment]
好的，谢谢
