### ISSUE TITLE
php7

### ISSUE THREAD

**Issue by andygithubchen** [Qihoo360/phptrace#60]
Makefile:214: recipe for target 'trace.lo' failed
make: **\* [trace.lo] Error 1

**Comment by slow-is-fast** [comment]
any updates?

**Comment by monque** [comment]
see https://github.com/monque/phptrace/tree/dev

still in **DEVELOPMENT**

**Comment by xianhuawei** [comment]
同求php7版本

**Comment by monque** [comment]
Current version `1.0.0-beta` supports PHP 7, you may download from http://pecl.php.net/trace or build from `master` branch.
