### ISSUE TITLE
umask 导致php进程调用命令行目录全部变为777

### ISSUE THREAD

**Issue by fifsky** [Qihoo360/phptrace#61]
https://github.com/Qihoo360/phptrace/blob/bf208850e7b36d564073799c9ecfe04b9f739d4b/common/trace_mmap.c#L82

这里的umask(000) 直接导致所有php调用exec("mkdir -p /tmp/test/a/") 的目录全部变为了777权限，这太暴力了

**Comment by monque** [comment]
#75
