### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by liukim** [Qihoo360/phptrace#62]
1、我按照说明进行安装，但是没看到测试结果输出：
[root@localhost cmdtool]# 
[root@localhost cmdtool]# 
[root@localhost cmdtool]# php -r 'for ($i = 0; $i < 100; $i++) usleep(10000);' & ./phptrace -p $!
[2] 18016

2、另外我使用 ./phptrace -s -p  测试时候，报了下面的错误：
[root@localhost cmdtool]# cat /var/run/php-fpm/php-fpm.pid 
17550
[root@localhost cmdtool]# 
[root@localhost cmdtool]# ./phptrace -s -p 17550
TRACE ERROR: Can not open /tmp/phptrace.comm.17550 to read, No such file or directory!
STACK ERROR: Can not fetch PHP status from extension, fallback to get stack by ptrace
STACK ERROR: dump status failed. maybe the process is not executing a php script
[root@localhost cmdtool]# 

3、后面查看phpinfo(); 发现trace插件的确安装上去了。

`
trace support       enabled

Directive   Local     Value Master     Value
trace.data_dir        /tmp                  /tmp
trace.dotrace       0                           0
trace.enable        1                           1
trace.recv_size     4m                      4m
trace.send_size    64m                      64m
`
4、运行make test得到的结果如下（没全部通过）：

[root@localhost extension]# make test

Build complete.
Don't forget to run 'make test'.
# 

PHP         : /usr/bin/php 
PHP_SAPI    : cli
PHP_VERSION : 5.3.3
ZEND_VERSION: 2.3.0
PHP_OS      : Linux - Linux localhost.localdomain 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64
INI actual  : /home/kiml/Downloads/phptrace-0.3.0/extension/tmp-php.ini
More .INIs  :  
CWD         : /home/kiml/Downloads/phptrace-0.3.0/extension
Extra dirs  : 
# VALGRIND    : Not used
# TIME START 2016-08-18 05:37:17

PASS Trace simple call with various types of argument [tests/trace_001.phpt] 
PASS Trace include, require, lambda, eval [tests/trace_002.phpt] 
PASS Trace Class and Object [tests/trace_003.phpt] 
PASS Trace various handlers [tests/trace_004.phpt] 
SKIP Trace signal handler [tests/trace_005.phpt] reason: trace_start() not exists
SKIP Trace call under namespace [tests/trace_006.phpt] reason: trace_start() not exists
SKIP Trace Closure [tests/trace_007.phpt] reason: trace_start() not exists
SKIP Trace magic method __callStatic, __invoke [tests/trace_008.phpt] reason: trace_start() not exists
PASS Trace call recursive [tests/trace_009.phpt] 
SKIP Trace call trigger by autoload  < 5.5 [tests/trace_010.phpt] reason: trace_start() not exists
SKIP Trace call trigger by autoload >= 5.5 [tests/trace_011.phpt] reason: trace_start() not exists
# SKIP Trace Trait [tests/trace_012.phpt] reason: trace_start() not exists

TIME END 2016-08-18 05:37:17
# 
## TEST RESULT SUMMARY

Exts skipped    :    0
## Exts tested     :   29

Number of tests :   12                 5
Tests skipped   :    7 ( 58.3%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
## Tests passed    :    5 ( 41.7%) (100.0%)
# Time taken      :    0 seconds

**Comment by nardoo** [comment]
我也遇到类似问题，运行 ./phptrace -s -p {进程ID}   提示TRACK ERROR， 然后就退出了

**Comment by bai471051357** [comment]
please use phptrace latest master branch
