### ISSUE TITLE
有问题

### ISSUE THREAD

**Issue by laojie** [Qihoo360/phptrace#63]
`[root@udev cmdtool]# sudo ./phptrace -s -p 19475
TRACE ERROR: Can not open /tmp/phptrace.comm.19475 to read, No such file or directory!
STACK ERROR: Can not fetch PHP status from extension, fallback to get stack by ptrace
INVALID PARAM: sapi-globals: <sapi_globals>`

**Comment by bai471051357** [comment]
please show me php and trace  version  ,  phptrace config in php.ini
