### ISSUE TITLE
phptrace

### ISSUE THREAD

**Issue by mengyilangan** [Qihoo360/phptrace#68]
I used latest master branch，
input ： phptrace -p 31409 -s
output ：phptrace: invalid option -- 's'

input：  phptrace --help
output
Options:
        --ptrace        Fetch data using ptrace, only in status mode
    -p, --pid           Process id
    -h, --help          Show this screen
    -v, --verbose
    -f, --filter        Filter data by type [url,function,class] and content
    -l, --limit         Limit output count

**Comment by bai471051357** [comment]
the latest version not support  "-s"

**Comment by monque** [comment]
```
phptrace - A low-overhead tracing tool for PHP

Usage: phptrace -p <pid>...
       phptrace -h | --help

Commands:
    trace               Trace a running PHP process [default]
    status              Display current status of specified PHP process
    version             Show version

Options:
        --ptrace        Fetch data using ptrace, only in status mode
    -p, --pid           Process id
    -h, --help          Show this screen
    -v, --verbose
```

For `phptrace -s` to output current running stack, instead by `phptrace stack` this version.
