### ISSUE TITLE
Invalid process id: 'xxxxxxx'

### ISSUE THREAD

**Issue by kobeng** [Qihoo360/phptrace#7]
大家好，

sysctl -a |grep pid_max

kernel.pid_max = 245760

我通过top查看占用cpu 99%的pid 这个pid当时侯为php-cli执行中

[phptrace/cmdtool]# ./phptrace -p 104459
Invalid process id: '104459'

如何修复这个bug？

谢谢。

**Comment by shafreeck** [comment]
你好，非常感谢您的反馈，当前默认定义最大pid为32768，以后我们回改为从kernel.pid_max读取。如果您急着使用，也可以手动修改源码中PID_MAX宏到合适的值，然后重新编译。

**Comment by shafreeck** [comment]
**notice**
由于代码开源前使用gitlab的issue系统， 因此这里自动关联的commit https://github.com/liuyuqiang/phptrace/commit/989b610cfe6d5a03073ff8124724f5af2efc2ea1 其实不正确。

**Comment by shafreeck** [comment]
resolved https://github.com/Qihoo360/phptrace/commit/373eafaf5982e88ea0523ad6b2288fde80364342
