### ISSUE TITLE
Mac 下支持 homebrew安装

### ISSUE THREAD

**Issue by shafreeck** [Qihoo360/phptrace#9]

**Comment by aiyuchen** [comment]
支持下啊，一定要支持homebrew啊，因为mac下包管理很好用，PHP及所有扩展都是homebrew管理的，这样方便升级，即便PHP更新了，扩展也不会受到影响，比如说：xdebug、php-redis等等

**Comment by fengqi** [comment]
ruby 脚本写的, 应该不难, 我研究下看看 😄

**Comment by monque** [comment]
恩，ok了发pr就好啦，谢谢

**Comment by monque** [comment]
恩，ok了发pr就好啦，谢谢
